### ISSUE TITLE
FAIRE LE TRIGGER DE COMBAT QUAND LE PERSO EST SUR UNE CASE AVEC UN MONSTRE

### ISSUE THREAD

**Issue by Thibaulltt** [Thibaulltt/CERI_software_engineering_game_1#79]
Cela implique :

- Faire une fonction qui vérifie si le joueur est sur une case occupée par un monstre **avant** de lui demander où il veut aller.
- Faire une fonction qui amorce le combat.
- Faire une condition dans la carte qui, une fois le monstre mort, met la case du monstre en inaccessible, puis change l'affichage de la carte (en modifiant io::updateMap() peut être ?)

**Comment by Thibaulltt** [comment]
**N.B.** : Désolé si ca vous a réveillé au milieu de la nuit si vous avez reçu un email concernant cette issue que je viens de soumettre au serveur, mais j'avais vraiment besoin de noter cette requête avant de l'oublier le lendemain matin.

**Comment by RaphAlreadyTaken** [comment]
Pas sûr pour la case monstre en inaccessible. Déjà, où est-ce qu'on met le joueur après le combat, vu que c'est devenu inaccessible? Sur une case à côté? De quel côté? Et si on le met d'un côté entouré d'obstacles, il est bloqué?
On pourrait faire en sorte que la case devienne inaccessible uniquement après que le joueur a bougé, mais là encore, selon où il va, il peut se retrouver bloqué.

Pour ma part, je voyais plus la case devenir "vide", voire avec un fond rouge pour représenter le sang, mais toujours accessible.

Pour la fonction déclenchement de combat, je compte m'en occuper, mais pas tout de suite, il faut que j'avance un peu Havannah. Faites-moi signe si vous vous y mettez.
Pour information, la fonction combat prend en entrée la chaîne d'ID du monstre, qui correspond au champ écrit dans le fichier, et donc au champ contenu dans la case, il suffit d'une condition. Vous pouvez vous reporter au main.cpp situé dans tests, qui contient tous les éléments nécessaires à une partie (sauf la partie déplacement, qui n'était pas encore codée).

P.S: je mets ce message en copie sur la discussion FB du projet

**Comment by Thibaulltt** [comment]
Voila ce que j'avais en tête : 

- le joueur engage un combat en entrant sur une case occupée par un monstre (celle ci est donc accessible sur le plateau). Cela évite plusieurs paradoxes que l'on pourrait avoir :
  - si le combat est amorcé quand le joueur est sur une case voisine à un monstre, mais qu'il se trouve sur une case avec 2 monstres dans sa vicinité, lequel choisir ?
  - si le combat est amorcé en entrant sur la case d'un monstre, mais que celles-ci sont inaccessibles, comment amorce-t'on un combat ?
- le joueur gagne ensuite le combat (si il gère bien sa barre de vie et de mana). La case sera donc rendue inaccessible, mais étant donné que la fonction de générations de mouvements regarde les cases voisine sans vérifier la case actuelle, le joueur peut se déplacer librement en dehors de la case du monstre

**Comment by Thibaulltt** [comment]
Ah et aussi, pendant qu'on est sur le sujet des actions de déclenchement d'autres actions, il faudrait aussi faire une fonction d'arrêt de la partie, afin que si le joueur appuie sur `ESC` pendant un input, que le jeu s'arrête (et se sauvegarde ???).

**Comment by RaphAlreadyTaken** [comment]
L'arrêt de partie, j'avoue y avoir réfléchi 10 secondes, et puis j'ai arrêté. Je note ça quelque part
